### ISSUE TITLE
Does not work with local OpenAI API

### ISSUE THREAD

**Issue by toby3d** [qwersyk/Newelle#70]
[oobabooga/text-generation-webui](/oobabooga/text-generation-webui), when run with the `--api` flag, publishes a locally available OpenAI API at http://127.0.0.1:5000/v1/. But trying to change the endpoint in the settings does not lead to anything: any requests result in the response "Connection error".

![image](https://github.com/user-attachments/assets/c195813f-ee3b-4399-a058-db386cd2343c)

SillyTavern accessing the same API works correctly. Specifying the model in the application settings or ignoring this setting does not affect the result either.

I run this app by this command:
```bash
$ flatpak run --talk-name=org.freedesktop.Flatpak --filesystem=home io.github.qwersyk.Newelle
```

**Comment by FrancescoCaracciolo** [comment]
Try putting something in the API Key section. It looks like openai python library (or the api) does not like it when you have nothing there

**Comment by FrancescoCaracciolo** [comment]
I have added a note about this in [the user guide to LLM](https://github.com/qwersyk/Newelle/wiki/User-guide-to-the-available-LLMs#open-ai-api). But soon I will make the code put automatically something in that field if the user does not specify it.

**Comment by toby3d** [comment]
> Try putting something in the API Key section. It looks like openai python library (or the api) does not like it when you have nothing there

Well, I enter `hackme` as stub token and now textgenui backend panics every time then it get request from Newelle:
```bash
Llama.generate: prefix-match hit
Traceback (most recent call last):                                                                                                                                                                        
  File "~/text-generation-webui/modules/callbacks.py", line 61, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/text-generation-webui/modules/llamacpp_model.py", line 175, in generate
    for completion_chunk in completion_chunks:
  File "~/text-generation-webui/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda_tensorcores/llama.py", line 1092, in _create_completion
    for token in self.generate(
  File "~/text-generation-webui/modules/llama_cpp_python_hijack.py", line 77, in my_generate
    for output in self.original_generate(*args, **kwargs):
  File "~/text-generation-webui/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda_tensorcores/llama.py", line 722, in generate
    token = self.sample(
            ^^^^^^^^^^^^
  File "~/text-generation-webui/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda_tensorcores/llama.py", line 641, in sample
    id = sampling_context.sample(ctx_main=self._ctx, logits_array=logits)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/text-generation-webui/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda_tensorcores/_internals.py", line 753, in sample
    ctx_main.sample_repetition_penalties(
  File "~/text-generation-webui/installer_files/env/lib/python3.11/site-packages/llama_cpp_cuda_tensorcores/_internals.py", line 356, in sample_repetition_penalties
    llama_cpp.llama_sample_repetition_penalties(
ctypes.ArgumentError: argument 6: TypeError: wrong type
Output generated in 0.79 seconds (0.00 tokens/s, 0 tokens, context 497, seed 30735305)
```

Not sure if I should contact the backend maintainer about working with the application if this is a protocol compatibility issue. On the other hand, if it's an API issue that the backend is trying to pretend to be, then it's definitely worth an issue at the source. 🤔

**Comment by FrancescoCaracciolo** [comment]
You should open an issue in text-generation-webui. I thing this is a bug on their side.
